### ISSUE TITLE
consider online course website

### ISSUE THREAD

**Issue by philbarresi** [stevens-cs546-cs554/CS-546#5]
We teach a web development course, so we should _probably_ do something cool.

We can do something like add react-pdf-js to make a PDF viewer, host demo code, and potentially allow some interactivity somehow to non DB lectures at least.

**Comment by philbarresi** [comment]
Would love to hear your thoughts.

**Comment by graffixnyc** [comment]
Ohh that would be VERY cool.  Maybe even add a threaded discussion to each topic page that can act as an extra resource for students, they can ask a question about that topic, or view past questions other students have asked. We can link to external resources too, docs and such. That way everything they need for a topic is accessible from one page.  The lecture, the code, external resources.  I think this would be a great idea.
